### ISSUE TITLE
can't preview database create by Room

### ISSUE THREAD

**Issue by camlot** [gitofleonardo/SimpleSqliteBrowser#1]
I create a project on Android and use Room to auto generate databases. Room has created three DB files named [sample.db, sample.db-shm, sample.db-wal], when I click to open sample.db, there is nothing show on Tables, but the database created by SQLiteOpenHelper [sample.db, sample.db-journal] is normal browsing.
Dose the browser support open files generated by Room? Or do you have a plan to add this func?

**Comment by deprecated-account1** [comment]
For databases created by room, you need an extra action to open them: Select the three database files [*.db/*.db-shm/*.db-wal] and then right-click you mouse and select `Save To`, then just save it to the default file path. After that, double-clicking the `*.db` file in `Device File Explorer` will successfully open the database file and read the content. The reason for that is, the sqlite driver needs the three files to fully read the database and these files have to be in the same directory. But intellij plugin cannot open multiple files in a `FileEditor` at a time. For more about sqlite file slices, please refer to this [official document](https://www.sqlite.org/tempfiles.html).

**Comment by camlot** [comment]
Thx for your reply and it really works!
